# -*- coding: utf-8 -*-
"""BOJ_11047.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xw0GXZU25b66UNWduXaXApY1-riGsInm
"""

n,k= map(int,input().split())
li=[]
result=0

for i in range(n):
  a=int(input())
  li.append(a)


li.sort()

for i in range(n-1,-1,-1):
  if (k//li[i]) !=0:
    result+= k//li[i]
    k%=li[i]



print(result)